/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutUserdashboardImport } from './routes/_layout/userdashboard'
import { Route as LayoutDashboardImport } from './routes/_layout/dashboard'
import { Route as LayoutUsersImport } from './routes/_layout/_users'
import { Route as LayoutDevicesImport } from './routes/_layout/_devices'
import { Route as AuthVerifyOtpImport } from './routes/_auth/verify-otp'
import { Route as AuthSigninPhoneImport } from './routes/_auth/signin-phone'
import { Route as LayoutDevicesDevicesIndexImport } from './routes/_layout/_devices/devices/index'
import { Route as LayoutUsersUsersUsersidDevicesImport } from './routes/_layout/_users/users/$users_id/_devices'
import { Route as LayoutDevicesDevicesDeviceidStarterboxImport } from './routes/_layout/_devices/devices/$device_id/starterbox'
import { Route as LayoutUsersUsersUsersidPondsPondsidIndexImport } from './routes/_layout/_users/users/$users_id/ponds/$ponds_id/index'
import { Route as LayoutDevicesDevicesDeviceidMotorsMotoridIndexImport } from './routes/_layout/_devices/devices/$device_id/motors/$motor_id/index'

// Create Virtual Routes

const LayoutUsersUsersUsersidImport = createFileRoute(
  '/_layout/_users/users/$users_id',
)()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutUserdashboardRoute = LayoutUserdashboardImport.update({
  id: '/userdashboard',
  path: '/userdashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUsersRoute = LayoutUsersImport.update({
  id: '/_users',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDevicesRoute = LayoutDevicesImport.update({
  id: '/_devices',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthVerifyOtpRoute = AuthVerifyOtpImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSigninPhoneRoute = AuthSigninPhoneImport.update({
  id: '/signin-phone',
  path: '/signin-phone',
  getParentRoute: () => AuthRoute,
} as any)

const LayoutUsersUsersUsersidRoute = LayoutUsersUsersUsersidImport.update({
  id: '/users/$users_id',
  path: '/users/$users_id',
  getParentRoute: () => LayoutUsersRoute,
} as any)

const LayoutDevicesDevicesIndexRoute = LayoutDevicesDevicesIndexImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => LayoutDevicesRoute,
} as any)

const LayoutUsersUsersUsersidDevicesRoute =
  LayoutUsersUsersUsersidDevicesImport.update({
    id: '/_devices',
    getParentRoute: () => LayoutUsersUsersUsersidRoute,
  } as any)

const LayoutDevicesDevicesDeviceidStarterboxRoute =
  LayoutDevicesDevicesDeviceidStarterboxImport.update({
    id: '/devices/$device_id/starterbox',
    path: '/devices/$device_id/starterbox',
    getParentRoute: () => LayoutDevicesRoute,
  } as any)

const LayoutUsersUsersUsersidPondsPondsidIndexRoute =
  LayoutUsersUsersUsersidPondsPondsidIndexImport.update({
    id: '/ponds/$ponds_id/',
    path: '/ponds/$ponds_id/',
    getParentRoute: () => LayoutUsersUsersUsersidRoute,
  } as any)

const LayoutDevicesDevicesDeviceidMotorsMotoridIndexRoute =
  LayoutDevicesDevicesDeviceidMotorsMotoridIndexImport.update({
    id: '/devices/$device_id/motors/$motor_id/',
    path: '/devices/$device_id/motors/$motor_id/',
    getParentRoute: () => LayoutDevicesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/signin-phone': {
      id: '/_auth/signin-phone'
      path: '/signin-phone'
      fullPath: '/signin-phone'
      preLoaderRoute: typeof AuthSigninPhoneImport
      parentRoute: typeof AuthImport
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpImport
      parentRoute: typeof AuthImport
    }
    '/_layout/_devices': {
      id: '/_layout/_devices'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutDevicesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_users': {
      id: '/_layout/_users'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutUsersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/userdashboard': {
      id: '/_layout/userdashboard'
      path: '/userdashboard'
      fullPath: '/userdashboard'
      preLoaderRoute: typeof LayoutUserdashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_devices/devices/': {
      id: '/_layout/_devices/devices/'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof LayoutDevicesDevicesIndexImport
      parentRoute: typeof LayoutDevicesImport
    }
    '/_layout/_devices/devices/$device_id/starterbox': {
      id: '/_layout/_devices/devices/$device_id/starterbox'
      path: '/devices/$device_id/starterbox'
      fullPath: '/devices/$device_id/starterbox'
      preLoaderRoute: typeof LayoutDevicesDevicesDeviceidStarterboxImport
      parentRoute: typeof LayoutDevicesImport
    }
    '/_layout/_users/users/$users_id': {
      id: '/_layout/_users/users/$users_id'
      path: '/users/$users_id'
      fullPath: '/users/$users_id'
      preLoaderRoute: typeof LayoutUsersUsersUsersidImport
      parentRoute: typeof LayoutUsersImport
    }
    '/_layout/_users/users/$users_id/_devices': {
      id: '/_layout/_users/users/$users_id/_devices'
      path: '/users/$users_id'
      fullPath: '/users/$users_id'
      preLoaderRoute: typeof LayoutUsersUsersUsersidDevicesImport
      parentRoute: typeof LayoutUsersUsersUsersidRoute
    }
    '/_layout/_devices/devices/$device_id/motors/$motor_id/': {
      id: '/_layout/_devices/devices/$device_id/motors/$motor_id/'
      path: '/devices/$device_id/motors/$motor_id'
      fullPath: '/devices/$device_id/motors/$motor_id'
      preLoaderRoute: typeof LayoutDevicesDevicesDeviceidMotorsMotoridIndexImport
      parentRoute: typeof LayoutDevicesImport
    }
    '/_layout/_users/users/$users_id/ponds/$ponds_id/': {
      id: '/_layout/_users/users/$users_id/ponds/$ponds_id/'
      path: '/ponds/$ponds_id'
      fullPath: '/users/$users_id/ponds/$ponds_id'
      preLoaderRoute: typeof LayoutUsersUsersUsersidPondsPondsidIndexImport
      parentRoute: typeof LayoutUsersUsersUsersidImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthSigninPhoneRoute: typeof AuthSigninPhoneRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninPhoneRoute: AuthSigninPhoneRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutDevicesRouteChildren {
  LayoutDevicesDevicesIndexRoute: typeof LayoutDevicesDevicesIndexRoute
  LayoutDevicesDevicesDeviceidStarterboxRoute: typeof LayoutDevicesDevicesDeviceidStarterboxRoute
  LayoutDevicesDevicesDeviceidMotorsMotoridIndexRoute: typeof LayoutDevicesDevicesDeviceidMotorsMotoridIndexRoute
}

const LayoutDevicesRouteChildren: LayoutDevicesRouteChildren = {
  LayoutDevicesDevicesIndexRoute: LayoutDevicesDevicesIndexRoute,
  LayoutDevicesDevicesDeviceidStarterboxRoute:
    LayoutDevicesDevicesDeviceidStarterboxRoute,
  LayoutDevicesDevicesDeviceidMotorsMotoridIndexRoute:
    LayoutDevicesDevicesDeviceidMotorsMotoridIndexRoute,
}

const LayoutDevicesRouteWithChildren = LayoutDevicesRoute._addFileChildren(
  LayoutDevicesRouteChildren,
)

interface LayoutUsersUsersUsersidRouteChildren {
  LayoutUsersUsersUsersidDevicesRoute: typeof LayoutUsersUsersUsersidDevicesRoute
  LayoutUsersUsersUsersidPondsPondsidIndexRoute: typeof LayoutUsersUsersUsersidPondsPondsidIndexRoute
}

const LayoutUsersUsersUsersidRouteChildren: LayoutUsersUsersUsersidRouteChildren =
  {
    LayoutUsersUsersUsersidDevicesRoute: LayoutUsersUsersUsersidDevicesRoute,
    LayoutUsersUsersUsersidPondsPondsidIndexRoute:
      LayoutUsersUsersUsersidPondsPondsidIndexRoute,
  }

const LayoutUsersUsersUsersidRouteWithChildren =
  LayoutUsersUsersUsersidRoute._addFileChildren(
    LayoutUsersUsersUsersidRouteChildren,
  )

interface LayoutUsersRouteChildren {
  LayoutUsersUsersUsersidRoute: typeof LayoutUsersUsersUsersidRouteWithChildren
}

const LayoutUsersRouteChildren: LayoutUsersRouteChildren = {
  LayoutUsersUsersUsersidRoute: LayoutUsersUsersUsersidRouteWithChildren,
}

const LayoutUsersRouteWithChildren = LayoutUsersRoute._addFileChildren(
  LayoutUsersRouteChildren,
)

interface LayoutRouteChildren {
  LayoutDevicesRoute: typeof LayoutDevicesRouteWithChildren
  LayoutUsersRoute: typeof LayoutUsersRouteWithChildren
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutUserdashboardRoute: typeof LayoutUserdashboardRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDevicesRoute: LayoutDevicesRouteWithChildren,
  LayoutUsersRoute: LayoutUsersRouteWithChildren,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutUserdashboardRoute: LayoutUserdashboardRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutUsersRouteWithChildren
  '/signin-phone': typeof AuthSigninPhoneRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/userdashboard': typeof LayoutUserdashboardRoute
  '/devices': typeof LayoutDevicesDevicesIndexRoute
  '/devices/$device_id/starterbox': typeof LayoutDevicesDevicesDeviceidStarterboxRoute
  '/users/$users_id': typeof LayoutUsersUsersUsersidDevicesRoute
  '/devices/$device_id/motors/$motor_id': typeof LayoutDevicesDevicesDeviceidMotorsMotoridIndexRoute
  '/users/$users_id/ponds/$ponds_id': typeof LayoutUsersUsersUsersidPondsPondsidIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutUsersRouteWithChildren
  '/signin-phone': typeof AuthSigninPhoneRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/userdashboard': typeof LayoutUserdashboardRoute
  '/devices': typeof LayoutDevicesDevicesIndexRoute
  '/devices/$device_id/starterbox': typeof LayoutDevicesDevicesDeviceidStarterboxRoute
  '/users/$users_id': typeof LayoutUsersUsersUsersidDevicesRoute
  '/devices/$device_id/motors/$motor_id': typeof LayoutDevicesDevicesDeviceidMotorsMotoridIndexRoute
  '/users/$users_id/ponds/$ponds_id': typeof LayoutUsersUsersUsersidPondsPondsidIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_auth/signin-phone': typeof AuthSigninPhoneRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_layout/_devices': typeof LayoutDevicesRouteWithChildren
  '/_layout/_users': typeof LayoutUsersRouteWithChildren
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/userdashboard': typeof LayoutUserdashboardRoute
  '/_layout/_devices/devices/': typeof LayoutDevicesDevicesIndexRoute
  '/_layout/_devices/devices/$device_id/starterbox': typeof LayoutDevicesDevicesDeviceidStarterboxRoute
  '/_layout/_users/users/$users_id': typeof LayoutUsersUsersUsersidRouteWithChildren
  '/_layout/_users/users/$users_id/_devices': typeof LayoutUsersUsersUsersidDevicesRoute
  '/_layout/_devices/devices/$device_id/motors/$motor_id/': typeof LayoutDevicesDevicesDeviceidMotorsMotoridIndexRoute
  '/_layout/_users/users/$users_id/ponds/$ponds_id/': typeof LayoutUsersUsersUsersidPondsPondsidIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/signin-phone'
    | '/verify-otp'
    | '/dashboard'
    | '/userdashboard'
    | '/devices'
    | '/devices/$device_id/starterbox'
    | '/users/$users_id'
    | '/devices/$device_id/motors/$motor_id'
    | '/users/$users_id/ponds/$ponds_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/signin-phone'
    | '/verify-otp'
    | '/dashboard'
    | '/userdashboard'
    | '/devices'
    | '/devices/$device_id/starterbox'
    | '/users/$users_id'
    | '/devices/$device_id/motors/$motor_id'
    | '/users/$users_id/ponds/$ponds_id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_layout'
    | '/_auth/signin-phone'
    | '/_auth/verify-otp'
    | '/_layout/_devices'
    | '/_layout/_users'
    | '/_layout/dashboard'
    | '/_layout/userdashboard'
    | '/_layout/_devices/devices/'
    | '/_layout/_devices/devices/$device_id/starterbox'
    | '/_layout/_users/users/$users_id'
    | '/_layout/_users/users/$users_id/_devices'
    | '/_layout/_devices/devices/$device_id/motors/$motor_id/'
    | '/_layout/_users/users/$users_id/ponds/$ponds_id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/signin-phone",
        "/_auth/verify-otp"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_devices",
        "/_layout/_users",
        "/_layout/dashboard",
        "/_layout/userdashboard"
      ]
    },
    "/_auth/signin-phone": {
      "filePath": "_auth/signin-phone.tsx",
      "parent": "/_auth"
    },
    "/_auth/verify-otp": {
      "filePath": "_auth/verify-otp.tsx",
      "parent": "/_auth"
    },
    "/_layout/_devices": {
      "filePath": "_layout/_devices.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_devices/devices/",
        "/_layout/_devices/devices/$device_id/starterbox",
        "/_layout/_devices/devices/$device_id/motors/$motor_id/"
      ]
    },
    "/_layout/_users": {
      "filePath": "_layout/_users.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_users/users/$users_id"
      ]
    },
    "/_layout/dashboard": {
      "filePath": "_layout/dashboard.tsx",
      "parent": "/_layout"
    },
    "/_layout/userdashboard": {
      "filePath": "_layout/userdashboard.tsx",
      "parent": "/_layout"
    },
    "/_layout/_devices/devices/": {
      "filePath": "_layout/_devices/devices/index.tsx",
      "parent": "/_layout/_devices"
    },
    "/_layout/_devices/devices/$device_id/starterbox": {
      "filePath": "_layout/_devices/devices/$device_id/starterbox.tsx",
      "parent": "/_layout/_devices"
    },
    "/_layout/_users/users/$users_id": {
      "filePath": "_layout/_users/users/$users_id",
      "parent": "/_layout/_users",
      "children": [
        "/_layout/_users/users/$users_id/_devices",
        "/_layout/_users/users/$users_id/ponds/$ponds_id/"
      ]
    },
    "/_layout/_users/users/$users_id/_devices": {
      "filePath": "_layout/_users/users/$users_id/_devices.tsx",
      "parent": "/_layout/_users/users/$users_id"
    },
    "/_layout/_devices/devices/$device_id/motors/$motor_id/": {
      "filePath": "_layout/_devices/devices/$device_id/motors/$motor_id/index.tsx",
      "parent": "/_layout/_devices"
    },
    "/_layout/_users/users/$users_id/ponds/$ponds_id/": {
      "filePath": "_layout/_users/users/$users_id/ponds/$ponds_id/index.tsx",
      "parent": "/_layout/_users/users/$users_id"
    }
  }
}
ROUTE_MANIFEST_END */
