// src/api/UsersData.ts
export const UserData = [
  {
    id: 1,
    username: "John Doe",
    userimage: "/assets/logo.svg",
    gateway: "AT&T",
    ponds_count: 5,
    pondsList: [
      {
        users_id: 1,
        pondId: "Pond-01",
        location: "Devarapalli",
        totalMotors: 5,
        motors: [
          {
            motorName: "Motor_001",
            horsePower: "5HP",
            deviceName: "Dev-001",
            managementStatus: "Scheduled",
          },
          {
            motorName: "Motor_002",
            horsePower: "7HP",
            deviceName: "Dev-002",
            managementStatus: "Manual",
          },
          {
            motorName: "Motor_003",
            horsePower: "3HP",
            deviceName: "Dev-003",
            managementStatus: "Auto",
          },
          {
            motorName: "Motor_004",
            horsePower: "4HP",
            deviceName: "Dev-004",
            managementStatus: "Scheduled",
          },
          {
            motorName: "Motor_005",
            horsePower: "6HP",
            deviceName: "Dev-005",
            managementStatus: "Manual",
          },
        ],
      },
      {
        users_id: 1,
        pondId: "Pond-02",
        location: "Devarapalli",
        totalMotors: 3,
        motors: [
          {
            motorName: "Motor_006",
            horsePower: "2HP",
            deviceName: "Dev-006",
            managementStatus: "Auto",
          },
          {
            motorName: "Motor_007",
            horsePower: "8HP",
            deviceName: "Dev-007",
            managementStatus: "Scheduled",
          },
          {
            motorName: "Motor_008",
            horsePower: "5HP",
            deviceName: "Dev-008",
            managementStatus: "Manual",
          },
        ],
      },
      {
        users_id: 1,
        pondId: "Pond-03",
        location: "Devarapalli",
        totalMotors: 0,
        motors: [],
      },
      {
        users_id: 1,
        pondId: "Pond-04",
        location: "Devarapalli",
        totalMotors: 1,
        motors: [
          {
            motorName: "Sensor_001",
            horsePower: "N/A",
            deviceName: "Dev-009",
            managementStatus: "Auto",
          },
        ],
      },
      {
        users_id: 1,
        pondId: "Pond-05",
        location: "Devarapalli",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_009",
            horsePower: "3HP",
            deviceName: "Dev-010",
            managementStatus: "Auto",
          },
          {
            motorName: "Motor_010",
            horsePower: "4HP",
            deviceName: "Dev-011",
            managementStatus: "Scheduled",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 1,
        apfc_id: "APFC-001",
        power_max_apfc: 50,
        location: "New York, NY",
        status: "online",
      },
      {
        user_id: 1,
        apfc_id: "APFC-002",
        power_max_apfc: 75,
        location: "Los Angeles, CA",
        status: "offline",
      },
    ],
    starterBoxList: [
      {
        user_id: 1,
        starterbox_id: "SB-001",
        device_id: "012345678",
        device_name: "Starter-001",
        power_rating: 60,
        location: "New York, NY",
        status: "Active",
      },
      {
        user_id: 1,
        starterbox_id: "SB-002",
        device_id: "012345679",
        device_name: "Starter-002",
        power_rating: 80,
        location: "Los Angeles, CA",
        status: "Inactive",
      },
    ],
  },
  {
    id: 2,
    username: "Jane Smith",
    userimage: "/assets/logo.svg",
    gateway: "Verizon",
    ponds_count: 3,
    pondsList: [
      {
        users_id: 2,
        pondId: "Pond-X",
        location: "Kakinada",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_011",
            horsePower: "1.2 kW",
            deviceName: "Dev-012",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 2,
        pondId: "Pond-Y",
        location: "Kakinada",
        totalMotors: 0,
        motors: [],
      },
      {
        users_id: 2,
        pondId: "Pond-Z",
        location: "Kakinada",
        totalMotors: 1,
        motors: [
          {
            motorName: "Sensor_002",
            horsePower: "N/A",
            deviceName: "Dev-013",
            managementStatus: "Inactive",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 2,
        apfc_id: "APFC-003",
        power_max_apfc: 100,
        location: "Chicago, IL",
        status: "online",
      },
    ],
    starterBoxList: [
      {
        user_id: 2,
        starterbox_id: "SB-003",
        device_id: "012345680",
        device_name: "Starter-003",
        power_rating: 70,
        location: "Chicago, IL",
        status: "Active",
      },
    ],
  },
  {
    id: 3,
    username: "Alice Johnson",
    userimage: "/assets/logo.svg",
    gateway: "T-Mobile",
    ponds_count: 7,
    pondsList: [
      {
        users_id: 3,
        pondId: "Pond-1",
        location: "Rajahmundry",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_012",
            horsePower: "2 kW",
            deviceName: "Dev-014",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_003",
            horsePower: "N/A",
            deviceName: "Dev-015",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 3,
        pondId: "Pond-2",
        location: "Rajahmundry",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_013",
            horsePower: "1.8 kW",
            deviceName: "Dev-016",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 3,
        pondId: "Pond-3",
        location: "Rajahmundry",
        totalMotors: 0,
        motors: [],
      },
      {
        users_id: 3,
        pondId: "Pond-4",
        location: "Rajahmundry",
        totalMotors: 1,
        motors: [
          {
            motorName: "Sensor_004",
            horsePower: "N/A",
            deviceName: "Dev-017",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 3,
        pondId: "Pond-5",
        location: "Rajahmundry",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_014",
            horsePower: "1.5 kW",
            deviceName: "Dev-018",
            managementStatus: "Inactive",
          },
        ],
      },
      {
        users_id: 3,
        pondId: "Pond-6",
        location: "Rajahmundry",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_015",
            horsePower: "1 kW",
            deviceName: "Dev-019",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 3,
        pondId: "Pond-7",
        location: "Rajahmundry",
        totalMotors: 0,
        motors: [],
      },
    ],
    apfcList: [
      {
        user_id: 3,
        apfc_id: "APFC-004",
        power_max_apfc: 120,
        location: "Houston, TX",
        status: "offline",
      },
      {
        user_id: 3,
        apfc_id: "APFC-005",
        power_max_apfc: 150,
        location: "Miami, FL",
        status: "online",
      },
      {
        user_id: 3,
        apfc_id: "APFC-006",
        power_max_apfc: 80,
        location: "London, UK",
        status: "offline",
      },
    ],
    starterBoxList: [
      {
        user_id: 3,
        starterbox_id: "SB-004",
        device_id: "012345681",
        device_name: "Starter-004",
        power_rating: 90,
        location: "Houston, TX",
        status: "Inactive",
      },
      {
        user_id: 3,
        starterbox_id: "SB-005",
        device_id: "012345682",
        device_name: "Starter-005",
        power_rating: 100,
        location: "Miami, FL",
        status: "Active",
      },
    ],
  },
  {
    id: 4,
    username: "Bob Wilson",
    userimage: "/assets/logo.svg",
    gateway: "Sprint",
    ponds_count: 2,
    pondsList: [
      {
        users_id: 4,
        pondId: "Pond-A",
        location: "Hyderabad",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_016",
            horsePower: "2 kW",
            deviceName: "Dev-020",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_005",
            horsePower: "N/A",
            deviceName: "Dev-021",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 4,
        pondId: "Pond-B",
        location: "Hyderabad",
        totalMotors: 0,
        motors: [],
      },
    ],
    apfcList: [
      {
        user_id: 4,
        apfc_id: "APFC-007",
        power_max_apfc: 60,
        location: "Toronto, Canada",
        status: "online",
      },
    ],
    starterBoxList: [
      {
        user_id: 4,
        starterbox_id: "SB-006",
        device_id: "012345683",
        device_name: "Starter-006",
        power_rating: 50,
        location: "Toronto, Canada",
        status: "Active",
      },
    ],
  },
  {
    id: 5,
    username: "Emma Davis",
    userimage: "/assets/logo.svg",
    gateway: "Vodafone",
    ponds_count: 4,
    pondsList: [
      {
        users_id: 5,
        pondId: "Pond-C",
        location: "Chennai",
        totalMotors: 3,
        motors: [
          {
            motorName: "Motor_017",
            horsePower: "1.5 kW",
            deviceName: "Dev-022",
            managementStatus: "Active",
          },
          {
            motorName: "Motor_018",
            horsePower: "2 kW",
            deviceName: "Dev-023",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_006",
            horsePower: "N/A",
            deviceName: "Dev-024",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 5,
        pondId: "Pond-D",
        location: "Chennai",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_019",
            horsePower: "1 kW",
            deviceName: "Dev-025",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 5,
        pondId: "Pond-E",
        location: "Chennai",
        totalMotors: 0,
        motors: [],
      },
      {
        users_id: 5,
        pondId: "Pond-F",
        location: "Chennai",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_020",
            horsePower: "3HP",
            deviceName: "Dev-026",
            managementStatus: "Auto",
          },
          {
            motorName: "Sensor_007",
            horsePower: "N/A",
            deviceName: "Dev-027",
            managementStatus: "Active",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 5,
        apfc_id: "APFC-008",
        power_max_apfc: 90,
        location: "Sydney, Australia",
        status: "offline",
      },
      {
        user_id: 5,
        apfc_id: "APFC-009",
        power_max_apfc: 110,
        location: "Tokyo, Japan",
        status: "online",
      },
    ],
    starterBoxList: [
      {
        user_id: 5,
        starterbox_id: "SB-007",
        device_id: "012345684",
        device_name: "Starter-007",
        power_rating: 85,
        location: "Sydney, Australia",
        status: "Inactive",
      },
      {
        user_id: 5,
        starterbox_id: "SB-008",
        device_id: "012345685",
        device_name: "Starter-008",
        power_rating: 95,
        location: "Tokyo, Japan",
        status: "Active",
      },
    ],
  },
  {
    id: 6,
    username: "Michael Brown",
    userimage: "/assets/logo.svg",
    gateway: "Airtel",
    ponds_count: 1,
    pondsList: [
      {
        users_id: 6,
        pondId: "Pond-G",
        location: "Delhi",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_021",
            horsePower: "2 kW",
            deviceName: "Dev-028",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_008",
            horsePower: "N/A",
            deviceName: "Dev-029",
            managementStatus: "Active",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 6,
        apfc_id: "APFC-010",
        power_max_apfc: 130,
        location: "Mumbai, India",
        status: "offline",
      },
    ],
    starterBoxList: [
      {
        user_id: 6,
        starterbox_id: "SB-009",
        device_id: "012345686",
        device_name: "Starter-009",
        power_rating: 110,
        location: "Mumbai, India",
        status: "Inactive",
      },
    ],
  },
  {
    id: 7,
    username: "Sarah Miller",
    userimage: "/assets/logo.svg",
    gateway: "Jio",
    ponds_count: 3,
    pondsList: [
      {
        users_id: 7,
        pondId: "Pond-H",
        location: "Bangalore",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_022",
            horsePower: "1.5 kW",
            deviceName: "Dev-030",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 7,
        pondId: "Pond-I",
        location: "Bangalore",
        totalMotors: 0,
        motors: [],
      },
      {
        users_id: 7,
        pondId: "Pond-J",
        location: "Bangalore",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_023",
            horsePower: "2 kW",
            deviceName: "Dev-031",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_009",
            horsePower: "N/A",
            deviceName: "Dev-032",
            managementStatus: "Active",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 7,
        apfc_id: "APFC-011",
        power_max_apfc: 70,
        location: "Paris, France",
        status: "online",
      },
      {
        user_id: 7,
        apfc_id: "APFC-012",
        power_max_apfc: 85,
        location: "Berlin, Germany",
        status: "offline",
      },
    ],
    starterBoxList: [
      {
        user_id: 7,
        starterbox_id: "SB-010",
        device_id: "012345687",
        device_name: "Starter-010",
        power_rating: 65,
        location: "Paris, France",
        status: "Active",
      },
      {
        user_id: 7,
        starterbox_id: "SB-011",
        device_id: "012345688",
        device_name: "Starter-011",
        power_rating: 75,
        location: "Berlin, Germany",
        status: "Inactive",
      },
    ],
  },
  {
    id: 8,
    username: "David Lee",
    userimage: "/assets/logo.svg",
    gateway: "Verizon",
    ponds_count: 2,
    pondsList: [
      {
        users_id: 8,
        pondId: "Pond-K",
        location: "Pune",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_024",
            horsePower: "1 kW",
            deviceName: "Dev-033",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 8,
        pondId: "Pond-L",
        location: "Pune",
        totalMotors: 0,
        motors: [],
      },
    ],
    apfcList: [
      {
        user_id: 8,
        apfc_id: "APFC-013",
        power_max_apfc: 95,
        location: "Cape Town, South Africa",
        status: "online",
      },
    ],
    starterBoxList: [
      {
        user_id: 8,
        starterbox_id: "SB-012",
        device_id: "012345689",
        device_name: "Starter-012",
        power_rating: 80,
        location: "Cape Town, South Africa",
        status: "Active",
      },
    ],
  },
  {
    id: 9,
    username: "Emily Clark",
    userimage: "/assets/logo.svg",
    gateway: "AT&T",
    ponds_count: 5,
    pondsList: [
      {
        users_id: 9,
        pondId: "Pond-M",
        location: "Kolkata",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_025",
            horsePower: "2 kW",
            deviceName: "Dev-034",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_010",
            horsePower: "N/A",
            deviceName: "Dev-035",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 9,
        pondId: "Pond-N",
        location: "Kolkata",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_026",
            horsePower: "1.5 kW",
            deviceName: "Dev-036",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 9,
        pondId: "Pond-O",
        location: "Kolkata",
        totalMotors: 0,
        motors: [],
      },
      {
        users_id: 9,
        pondId: "Pond-P",
        location: "Kolkata",
        totalMotors: 1,
        motors: [
          {
            motorName: "Sensor_011",
            horsePower: "N/A",
            deviceName: "Dev-037",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 9,
        pondId: "Pond-Q",
        location: "Kolkata",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_027",
            horsePower: "3HP",
            deviceName: "Dev-038",
            managementStatus: "Auto",
          },
          {
            motorName: "Motor_028",
            horsePower: "4HP",
            deviceName: "Dev-039",
            managementStatus: "Scheduled",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 9,
        apfc_id: "APFC-014",
        power_max_apfc: 140,
        location: "Dubai, UAE",
        status: "offline",
      },
      {
        user_id: 9,
        apfc_id: "APFC-015",
        power_max_apfc: 55,
        location: "Singapore",
        status: "online",
      },
    ],
    starterBoxList: [
      {
        user_id: 9,
        starterbox_id: "SB-013",
        device_id: "012345690",
        device_name: "Starter-013",
        power_rating: 120,
        location: "Dubai, UAE",
        status: "Inactive",
      },
      {
        user_id: 9,
        starterbox_id: "SB-014",
        device_id: "012345691",
        device_name: "Starter-014",
        power_rating: 50,
        location: "Singapore",
        status: "Active",
      },
    ],
  },
  {
    id: 10,
    username: "James White",
    userimage: "/assets/logo.svg",
    gateway: "Sprint",
    ponds_count: 1,
    pondsList: [
      {
        users_id: 10,
        pondId: "Pond-R",
        location: "Ahmedabad",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_029",
            horsePower: "2 kW",
            deviceName: "Dev-040",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_012",
            horsePower: "N/A",
            deviceName: "Dev-041",
            managementStatus: "Active",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 10,
        apfc_id: "APFC-016",
        power_max_apfc: 65,
        location: "Sao Paulo, Brazil",
        status: "offline",
      },
    ],
    starterBoxList: [
      {
        user_id: 10,
        starterbox_id: "SB-015",
        device_id: "012345692",
        device_name: "Starter-015",
        power_rating: 55,
        location: "Sao Paulo, Brazil",
        status: "Inactive",
      },
    ],
  },
  {
    id: 11,
    username: "Laura Martinez",
    userimage: "/assets/logo.svg",
    gateway: "Vodafone",
    ponds_count: 3,
    pondsList: [
      {
        users_id: 11,
        pondId: "Pond-S",
        location: "Jaipur",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_030",
            horsePower: "1.5 kW",
            deviceName: "Dev-042",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 11,
        pondId: "Pond-T",
        location: "Jaipur",
        totalMotors: 0,
        motors: [],
      },
      {
        users_id: 11,
        pondId: "Pond-U",
        location: "Jaipur",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_031",
            horsePower: "2 kW",
            deviceName: "Dev-043",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_013",
            horsePower: "N/A",
            deviceName: "Dev-044",
            managementStatus: "Active",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 11,
        apfc_id: "APFC-017",
        power_max_apfc: 115,
        location: "Mexico City, Mexico",
        status: "online",
      },
      {
        user_id: 11,
        apfc_id: "APFC-018",
        power_max_apfc: 125,
        location: "Bangkok, Thailand",
        status: "offline",
      },
    ],
    starterBoxList: [
      {
        user_id: 11,
        starterbox_id: "SB-016",
        device_id: "012345693",
        device_name: "Starter-016",
        power_rating: 100,
        location: "Mexico City, Mexico",
        status: "Active",
      },
      {
        user_id: 11,
        starterbox_id: "SB-017",
        device_id: "012345694",
        device_name: "Starter-017",
        power_rating: 110,
        location: "Bangkok, Thailand",
        status: "Inactive",
      },
    ],
  },
  {
    id: 12,
    username: "Thomas Harris",
    userimage: "/assets/logo.svg",
    gateway: "Airtel",
    ponds_count: 2,
    pondsList: [
      {
        users_id: 12,
        pondId: "Pond-V",
        location: "Lucknow",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_032",
            horsePower: "1 kW",
            deviceName: "Dev-045",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 12,
        pondId: "Pond-W",
        location: "Lucknow",
        totalMotors: 0,
        motors: [],
      },
    ],
    apfcList: [
      {
        user_id: 12,
        apfc_id: "APFC-019",
        power_max_apfc: 145,
        location: "Moscow, Russia",
        status: "online",
      },
    ],
    starterBoxList: [
      {
        user_id: 12,
        starterbox_id: "SB-018",
        device_id: "012345695",
        device_name: "Starter-018",
        power_rating: 130,
        location: "Moscow, Russia",
        status: "Active",
      },
    ],
  },
  {
    id: 13,
    username: "Sophia Lewis",
    userimage: "/assets/logo.svg",
    gateway: "Jio",
    ponds_count: 4,
    pondsList: [
      {
        users_id: 13,
        pondId: "Pond-X1",
        location: "Nagpur",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_033",
            horsePower: "2 kW",
            deviceName: "Dev-046",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_014",
            horsePower: "N/A",
            deviceName: "Dev-047",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 13,
        pondId: "Pond-X2",
        location: "Nagpur",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_034",
            horsePower: "1.5 kW",
            deviceName: "Dev-048",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 13,
        pondId: "Pond-X3",
        location: "Nagpur",
        totalMotors: 0,
        motors: [],
      },
      {
        users_id: 13,
        pondId: "Pond-X4",
        location: "Nagpur",
        totalMotors: 1,
        motors: [
          {
            motorName: "Sensor_015",
            horsePower: "N/A",
            deviceName: "Dev-049",
            managementStatus: "Active",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 13,
        apfc_id: "APFC-020",
        power_max_apfc: 135,
        location: "Seoul, South Korea",
        status: "offline",
      },
      {
        user_id: 13,
        apfc_id: "APFC-021",
        power_max_apfc: 50,
        location: "New York, NY",
        status: "online",
      },
    ],
    starterBoxList: [
      {
        user_id: 13,
        starterbox_id: "SB-019",
        device_id: "012345696",
        device_name: "Starter-019",
        power_rating: 115,
        location: "Seoul, South Korea",
        status: "Inactive",
      },
      {
        user_id: 13,
        starterbox_id: "SB-020",
        device_id: "012345697",
        device_name: "Starter-020",
        power_rating: 45,
        location: "New York, NY",
        status: "Active",
      },
    ],
  },
  {
    id: 14,
    username: "William Walker",
    userimage: "/assets/logo.svg",
    gateway: "Verizon",
    ponds_count: 2,
    pondsList: [
      {
        users_id: 14,
        pondId: "Pond-Y1",
        location: "Patna",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_035",
            horsePower: "1 kW",
            deviceName: "Dev-050",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 14,
        pondId: "Pond-Y2",
        location: "Patna",
        totalMotors: 0,
        motors: [],
      },
    ],
    apfcList: [
      {
        user_id: 14,
        apfc_id: "APFC-022",
        power_max_apfc: 75,
        location: "Los Angeles, CA",
        status: "offline",
      },
    ],
    starterBoxList: [
      {
        user_id: 14,
        starterbox_id: "SB-021",
        device_id: "012345698",
        device_name: "Starter-021",
        power_rating: 60,
        location: "Los Angeles, CA",
        status: "Inactive",
      },
    ],
  },
  {
    id: 15,
    username: "Ava King",
    userimage: "/assets/logo.svg",
    gateway: "AT&T",
    ponds_count: 3,
    pondsList: [
      {
        users_id: 15,
        pondId: "Pond-Z1",
        location: "Bhopal",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_036",
            horsePower: "2 kW",
            deviceName: "Dev-051",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_016",
            horsePower: "N/A",
            deviceName: "Dev-052",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 15,
        pondId: "Pond-Z2",
        location: "Bhopal",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_037",
            horsePower: "1.5 kW",
            deviceName: "Dev-053",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 15,
        pondId: "Pond-Z3",
        location: "Bhopal",
        totalMotors: 0,
        motors: [],
      },
    ],
    apfcList: [
      {
        user_id: 15,
        apfc_id: "APFC-023",
        power_max_apfc: 100,
        location: "Chicago, IL",
        status: "online",
      },
      {
        user_id: 15,
        apfc_id: "APFC-024",
        power_max_apfc: 120,
        location: "Houston, TX",
        status: "offline",
      },
    ],
    starterBoxList: [
      {
        user_id: 15,
        starterbox_id: "SB-022",
        device_id: "012345699",
        device_name: "Starter-022",
        power_rating: 90,
        location: "Chicago, IL",
        status: "Active",
      },
      {
        user_id: 15,
        starterbox_id: "SB-023",
        device_id: "012345700",
        device_name: "Starter-023",
        power_rating: 100,
        location: "Houston, TX",
        status: "Inactive",
      },
    ],
  },
  {
    id: 16,
    username: "Liam Hall",
    userimage: "/assets/logo.svg",
    gateway: "Sprint",
    ponds_count: 1,
    pondsList: [
      {
        users_id: 16,
        pondId: "Pond-A1",
        location: "Indore",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_038",
            horsePower: "2 kW",
            deviceName: "Dev-054",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_017",
            horsePower: "N/A",
            deviceName: "Dev-055",
            managementStatus: "Active",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 16,
        apfc_id: "APFC-025",
        power_max_apfc: 150,
        location: "Miami, FL",
        status: "online",
      },
    ],
    starterBoxList: [
      {
        user_id: 16,
        starterbox_id: "SB-024",
        device_id: "012345701",
        device_name: "Starter-024",
        power_rating: 130,
        location: "Miami, FL",
        status: "Active",
      },
    ],
  },
  {
    id: 17,
    username: "Olivia Scott",
    userimage: "/assets/logo.svg",
    gateway: "Vodafone",
    ponds_count: 4,
    pondsList: [
      {
        users_id: 17,
        pondId: "Pond-B1",
        location: "Surat",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_039",
            horsePower: "2 kW",
            deviceName: "Dev-056",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_018",
            horsePower: "N/A",
            deviceName: "Dev-057",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 17,
        pondId: "Pond-B2",
        location: "Surat",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_040",
            horsePower: "1.5 kW",
            deviceName: "Dev-058",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 17,
        pondId: "Pond-B3",
        location: "Surat",
        totalMotors: 0,
        motors: [],
      },
      {
        users_id: 17,
        pondId: "Pond-B4",
        location: "Surat",
        totalMotors: 1,
        motors: [
          {
            motorName: "Sensor_019",
            horsePower: "N/A",
            deviceName: "Dev-059",
            managementStatus: "Active",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 17,
        apfc_id: "APFC-026",
        power_max_apfc: 80,
        location: "London, UK",
        status: "offline",
      },
      {
        user_id: 17,
        apfc_id: "APFC-027",
        power_max_apfc: 60,
        location: "Toronto, Canada",
        status: "online",
      },
    ],
    starterBoxList: [
      {
        user_id: 17,
        starterbox_id: "SB-025",
        device_id: "012345702",
        device_name: "Starter-025",
        power_rating: 70,
        location: "London, UK",
        status: "Inactive",
      },
      {
        user_id: 17,
        starterbox_id: "SB-026",
        device_id: "012345703",
        device_name: "Starter-026",
        power_rating: 55,
        location: "Toronto, Canada",
        status: "Active",
      },
    ],
  },
  {
    id: 18,
    username: "Noah Green",
    userimage: "/assets/logo.svg",
    gateway: "Airtel",
    ponds_count: 2,
    pondsList: [
      {
        users_id: 18,
        pondId: "Pond-C1",
        location: "Vadodara",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_041",
            horsePower: "1 kW",
            deviceName: "Dev-060",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 18,
        pondId: "Pond-C2",
        location: "Vadodara",
        totalMotors: 0,
        motors: [],
      },
    ],
    apfcList: [
      {
        user_id: 18,
        apfc_id: "APFC-028",
        power_max_apfc: 90,
        location: "Sydney, Australia",
        status: "offline",
      },
    ],
    starterBoxList: [
      {
        user_id: 18,
        starterbox_id: "SB-027",
        device_id: "012345704",
        device_name: "Starter-027",
        power_rating: 80,
        location: "Sydney, Australia",
        status: "Inactive",
      },
    ],
  },
  {
    id: 19,
    username: "Mia Adams",
    userimage: "/assets/logo.svg",
    gateway: "Jio",
    ponds_count: 3,
    pondsList: [
      {
        users_id: 19,
        pondId: "Pond-D1",
        location: "Coimbatore",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_042",
            horsePower: "2 kW",
            deviceName: "Dev-061",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_020",
            horsePower: "N/A",
            deviceName: "Dev-062",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 19,
        pondId: "Pond-D2",
        location: "Coimbatore",
        totalMotors: 1,
        motors: [
          {
            motorName: "Motor_043",
            horsePower: "1.5 kW",
            deviceName: "Dev-063",
            managementStatus: "Active",
          },
        ],
      },
      {
        users_id: 19,
        pondId: "Pond-D3",
        location: "Coimbatore",
        totalMotors: 0,
        motors: [],
      },
    ],
    apfcList: [
      {
        user_id: 19,
        apfc_id: "APFC-029",
        power_max_apfc: 110,
        location: "Tokyo, Japan",
        status: "online",
      },
      {
        user_id: 19,
        apfc_id: "APFC-030",
        power_max_apfc: 130,
        location: "Mumbai, India",
        status: "offline",
      },
    ],
    starterBoxList: [
      {
        user_id: 19,
        starterbox_id: "SB-028",
        device_id: "012345705",
        device_name: "Starter-028",
        power_rating: 95,
        location: "Tokyo, Japan",
        status: "Active",
      },
      {
        user_id: 19,
        starterbox_id: "SB-029",
        device_id: "012345706",
        device_name: "Starter-029",
        power_rating: 115,
        location: "Mumbai, India",
        status: "Inactive",
      },
    ],
  },
  {
    id: 20,
    username: "Ethan Turner",
    userimage: "/assets/logo.svg",
    gateway: "Verizon",
    ponds_count: 1,
    pondsList: [
      {
        users_id: 20,
        pondId: "Pond-E1",
        location: "Visakhapatnam",
        totalMotors: 2,
        motors: [
          {
            motorName: "Motor_044",
            horsePower: "2 kW",
            deviceName: "Dev-064",
            managementStatus: "Active",
          },
          {
            motorName: "Sensor_021",
            horsePower: "N/A",
            deviceName: "Dev-065",
            managementStatus: "Active",
          },
        ],
      },
    ],
    apfcList: [
      {
        user_id: 20,
        apfc_id: "APFC-031",
        power_max_apfc: 70,
        location: "Paris, France",
        status: "online",
      },
    ],
    starterBoxList: [
      {
        user_id: 20,
        starterbox_id: "SB-030",
        device_id: "012345707",
        device_name: "Starter-030",
        power_rating: 60,
        location: "Paris, France",
        status: "Active",
      },
    ],
  },
];
